debug: off
logging:
  level:
    org.gamedo : info

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 7273

gamedo:
  metrics:
    enable: true

app.entity.count: 2000